version: '3'

services:
  zf:
    build: docker/apache-php
    ports:
      - 8080:80
    volumes:
      - .:/var/www/chat
      - ./docker/apache-php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/data/apache/log:/var/log/apache2
