<div class="row">
    <div class="col-md-12 message">
        <div class="alert alert-success alert-dismissible connect" role="alert" style="display: none">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Successful Connection</strong>
        </div>
        <div class="alert alert-danger alert-dismissible disconnect" role="alert" style="display: none">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Lost Connection</strong>
        </div>
        <form id="chat-form" class="form-horizontal" method="post">
            <div class="form-group">
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-1">
                    <input name="message" class="form-control" id="message" type="text" placeholder="Let's type something here!">
                </div>
                <button class="btn btn-success">Send</button>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="bs-message">
            <table class="table">
                <thead>
                    <tr>
                        <th>Created</th>
                        <th>Text</th>
                    </tr>
                </thead>
                <tbody>
                   <?php foreach ($this->messages as $message) : ?>
                        <tr>
                            <td><?= $this->escapeHtml($message['created']) ?></td>
                            <td><?= $this->escapeHtml($message['text']) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
